- hosts: all
  gather_facts: no
  become: yes
  vars_files:
  - cred.yml
  tasks:
  - name:
    pip:
      name: boto
      state: present

  - name: Creating Security Group for WebServer on AWS
    ec2_group:
      name: WebSG
      description: Security Group for Web Server allowing port for http and ssh
      region: ap-south-1
      aws_access_key: "{{ access_key }}"
      aws_secret_key: "{{ secret_key }}"
      rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0

  - name: launching ec2 instance for webserver
    ec2:
      instance_type: t2.micro
      key_name: kiyansh
      image: ami-08df646e18b182346
      wait: true
      count: 1
      vpc_subnet_id: subnet-0e92f58cfeda0d21c
      assign_public_ip: yes
      state: present
      region: ap-south-1
      aws_access_key: "{{ access_key }}"
      aws_secret_key: "{{ secret_key }}"
      instance_tags:
        Name: webserver
    register: ec2

  - name: Add new instance to host group
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: webserver
    loop: "{{ ec2.instances }}"

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      state: started
    loop: "{{ ec2.instances }}"

- hosts: webserver
  gather_facts: no
  tasks:
  - name: running role
    include_role:
      name: httpdserver
